version: '3.4'
services:
  db:
    image: 'bitnami/postgresql:latest'
    container_name: grendel-db
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_DATABASE=grendel
    ports:
      - '5432:5432'
    networks:
      - app-tier
    volumes:
      - 'postgres_data:/bitnami/postgresql'

  server:
    build: ./server
    depends_on:
      - db
    ports:
      - '8080:80'
    networks:
      - app-tier

  client:
    build: ./client
    ports:
    - '80:80'

networks:
  app-tier:
    driver: bridge

volumes:
  postgres_data:
    driver: local
