version: '3.4'
services:
  db:
    image: 'bitnami/postgresql:latest'
    container_name: grendel-db
    environment:
      - POSTGRESQL_USERNAME="${DB_USERNAME}"
      - POSTGRESQL_PASSWORD="${DB_PASSWORD}"
      - POSTGRESQL_DATABASE="${DB_DATABASE}"
    expose:
      - '5432'
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-tier
    volumes:
      - 'postgres_data:/bitnami/postgresql'
    restart: always

  api:
    build: ./server
    container_name: grendel-api
    depends_on:
      - db
      - client
    expose:
      - '80'
    networks:
      - app-tier
    restart: always

  client:
    build: ./client
    container_name: grendel-client
    ports:
    - '80:80'
    - '443:443'
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    driver: bridge

volumes:
  postgres_data:
    driver: local
