version: '3'
services:
  db:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_DATABASE=grendel
    ports:
      - '5000:5432'
    volumes:
      - 'postgres_data:/bitnami/postgresql'

  server:
    build: ./server
    depends_on:
      - db
    ports:
      - '8080:80'

  client:
    build: ./client
    ports:
    - '80:80'

volumes:
  postgres_data:
    driver: local
